In [1]:
import pandas as pd

In [2]:
from google.colab import files
files.upload()

Saving clientes_credito_preparacao_ml.csv to clientes_credito_preparacao_ml.csv

{'clientes_credito_preparacao_ml.csv': b'\xef\xbb\xbfid,nome,idade,renda,divida,estado_civil,aprovado\r\n1,Ana,25,3200,1200,Solteiro,Sim\r\n2,Bruno,42,8500,2500,Casado,Sim\r\n3,Carla,31,,4200,Solteiro,N\xc3\xa3o\r\n4,Daniel,19,1800,800,solteiro,N\xc3\xa3o\r\n5,Eduarda,150,5000,1500,Casado,Sim\r\n6,Felipe,37,6200,2800,CASADO,Sim\r\n7,Gabriela,29,4100,-500,Solteiro,N\xc3\xa3o\r\n8,Henrique,48,12000,3500,Divorciado,Sim\r\n9,Isabela,34,7200,2100,Casado,Sim\r\n10,Jo\xc3\xa3o,23,2600,1800,Solteiro,N\xc3\xa3o\r\n11,Karen,51,95000,4000,Casado,Sim\r\n12,Lucas,28,3900,2400,Solteiro,N\xc3\xa3o\r\n13,Mariana,39,9000,2700,Casado,Sim\r\n14,Nicolas,33,5400,3100,Divorciado,N\xc3\xa3o\r\n15,Olivia,45,11000,1900,Casado,Sim\r\n16,Paulo,26,3000,2200,Solteiro,N\xc3\xa3o\r\n8,Henrique,48,12000,3500,Divorciado,Sim\r\n'}

In [7]:
df = pd.read_csv("clientes_credito_preparacao_ml.csv")

df.head(10)

   id      nome  idade    renda  divida estado_civil aprovado
0   1       Ana     25   3200.0    1200     Solteiro      Sim
1   2     Bruno     42   8500.0    2500       Casado      Sim
2   3     Carla     31      NaN    4200     Solteiro      Não
3   4    Daniel     19   1800.0     800     solteiro      Não
4   5   Eduarda    150   5000.0    1500       Casado      Sim
5   6    Felipe     37   6200.0    2800       CASADO      Sim
6   7  Gabriela     29   4100.0    -500     Solteiro      Não
7   8  Henrique     48  12000.0    3500   Divorciado      Sim
8   9   Isabela     34   7200.0    2100       Casado      Sim
9  10      João     23   2600.0    1800     Solteiro      Não

In [8]:
# Conhecendo os dados

# Quantidade de registros
# Tipos das colunas
# Valores faltantes
# Valores min, max e categorias

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            17 non-null     int64
 1   nome          17 non-null     object
 2   idade         17 non-null     int64
 3   renda         16 non-null     float64
 4   divida        17 non-null     int64
 5   estado_civil  17 non-null     object
 6   aprovado      17 non-null     object
dtypes: float64(1), int64(3), object(3)
memory usage: 1.1+ KB

In [9]:
df.describe(include="all")

,id,nome,idade,renda,divida,estado_civil,aprovado
count,17.000000,17,17.000000,16.000000,17.000000,17,17
unique,NaN,16,NaN,NaN,NaN,5,2
top,NaN,Henrique,NaN,NaN,NaN,Solteiro,Sim
freq,NaN,2,NaN,NaN,NaN,6,10
mean,8.470588,NaN,41.647059,11868.750000,2335.294118,NaN,NaN
std,4.611367,NaN,29.499875,22418.852743,1195.272551,NaN,NaN
min,1.000000,NaN,19.000000,1800.000000,-500.000000,NaN,NaN
25%,5.000000,NaN,28.000000,3725.000000,1800.000000,NaN,NaN
50%,8.000000,NaN,34.000000,5800.000000,2400.000000,NaN,NaN
75%,12.000000,NaN,45.000000,9500.000000,3100.000000,NaN,NaN
max,16.000000,NaN,150.000000,95000.000000,4200.000000,NaN,NaN

In [10]:
df.isnull().sum()

id              0
nome            0
idade           0
renda           1
divida          0
estado_civil    0
aprovado        0
dtype: int64

In [12]:
# Categorias inconsistentes
# ex: Casado, CASADO e casado = são todos a mesma coisa
df["estado_civil"].value_counts()

estado_civil
Solteiro      6
Casado        6
Divorciado    3
solteiro      1
CASADO        1
Name: count, dtype: int64

In [16]:
# Valores suspeitos

df[["idade","renda","divida",]].describe()

            idade         renda       divida
count   17.000000     16.000000    17.000000
mean    41.647059  11868.750000  2335.294118
std     29.499875  22418.852743  1195.272551
min     19.000000   1800.000000  -500.000000
25%     28.000000   3725.000000  1800.000000
50%     34.000000   5800.000000  2400.000000
75%     45.000000   9500.000000  3100.000000
max    150.000000  95000.000000  4200.000000

In [20]:
# Fazer uma limpeza

# Corrigir as categorias
df["estado_civil"] = (df["estado_civil"].str.strip().str.lower())

df["estado_civil"].value_counts()

estado_civil
solteiro      7
casado        7
divorciado    3
Name: count, dtype: int64

In [24]:
# Tratar a renda ausente

df["renda"] = df["renda"].fillna(df["renda"].mean())
df.head()

   id     nome  idade     renda  divida estado_civil aprovado
0   1      Ana     25   3200.00    1200     solteiro      Sim
1   2    Bruno     42   8500.00    2500       casado      Sim
2   3    Carla     31  11868.75    4200     solteiro      Não
3   4   Daniel     19   1800.00     800     solteiro      Não
4   5  Eduarda    150   5000.00    1500       casado      Sim

In [71]:
# Tratar os valores inválidos
df.loc[df["idade"] > 90, "idade"] = df["idade"].mean().astype(int)
df.loc[df["divida"] < 0, "divida"] = df["divida"].mean()
df.head(20)

,id,nome,idade,renda,divida,estado_civil,aprovado,comprometimento_renda
0,1,Ana,25.000000,3200.00,1200.000000,solteiro,Sim,0.375000
1,2,Bruno,42.000000,8500.00,2500.000000,casado,Sim,0.294118
2,3,Carla,31.000000,11868.75,4200.000000,solteiro,Não,0.353870
3,4,Daniel,19.000000,1800.00,800.000000,solteiro,Não,0.444444
4,5,Eduarda,41.647059,5000.00,1500.000000,casado,Sim,0.300000
5,6,Felipe,37.000000,6200.00,2800.000000,casado,Sim,0.451613
6,7,Gabriela,29.000000,4100.00,2335.294118,solteiro,Não,0.569584
7,8,Henrique,48.000000,12000.00,3500.000000,divorciado,Sim,0.291667
8,9,Isabela,34.000000,7200.00,2100.000000,casado,Sim,0.291667
9,10,João,23.000000,2600.00,1800.000000,solteiro,Não,0.692308
10,11,Karen,51.000000,95000.00,4000.000000,casado,Sim,0.042105
11,12,Lucas,28.000000,3900.00,2400.000000,solteiro,Não,0.615385
12,13,Mariana,39.000000,9000.00,2700.000000,casado,Sim,0.300000
13,14,Nicolas,33.000000,5400.00,3100.000000,divorciado,Não,0.574074
14,15,Olivia,45.000000,11000.00,1900.000000,casado,Sim,0.172727
15,16,Paulo,26.000000,3000.00,2200.000000,solteiro,Não,0.733333

In [56]:
# Remover os registros duplicados
print("Duplicados: ", df.duplicated().sum())
df = df.drop_duplicates().reset_index(drop=True)
df.head(20)

Duplicados:  1

    id      nome      idade     renda       divida estado_civil aprovado
0    1       Ana  25.000000   3200.00  1200.000000     solteiro      Sim
1    2     Bruno  42.000000   8500.00  2500.000000       casado      Sim
2    3     Carla  31.000000  11868.75  4200.000000     solteiro      Não
3    4    Daniel  19.000000   1800.00   800.000000     solteiro      Não
4    5   Eduarda  41.647059   5000.00  1500.000000       casado      Sim
5    6    Felipe  37.000000   6200.00  2800.000000       casado      Sim
6    7  Gabriela  29.000000   4100.00  2335.294118     solteiro      Não
7    8  Henrique  48.000000  12000.00  3500.000000   divorciado      Sim
8    9   Isabela  34.000000   7200.00  2100.000000       casado      Sim
9   10      João  23.000000   2600.00  1800.000000     solteiro      Não
10  11     Karen  51.000000  95000.00  4000.000000       casado      Sim
11  12     Lucas  28.000000   3900.00  2400.000000     solteiro      Não
12  13   Mariana  39.000000   9000.00  2700.000000       casado      Sim
13  14   Nicolas  33.000000   5400.00  3100.000000   divorciado      Não
14  15    Olivia  45.000000  11000.00  1900.000000       casado      Sim
15  16     Paulo  26.000000   3000.00  2200.000000     solteiro      Não

In [76]:
#  Criar uma nova informação
df["comprometimento_renda"] = df["divida"] / df["renda"]
df[["renda","divida","comprometimento_renda","aprovado"]].head(10)

      renda       divida  comprometimento_renda aprovado
0   3200.00  1200.000000               0.375000      Sim
1   8500.00  2500.000000               0.294118      Sim
2  11868.75  4200.000000               0.353870      Não
3   1800.00   800.000000               0.444444      Não
4   5000.00  1500.000000               0.300000      Sim
5   6200.00  2800.000000               0.451613      Sim
6   4100.00  2335.294118               0.569584      Não
7  12000.00  3500.000000               0.291667      Sim
8   7200.00  2100.000000               0.291667      Sim
9   2600.00  1800.000000               0.692308      Não